### ISSUE TITLE
VSCode Extension not showing shiny run button

### ISSUE THREAD

**Issue by djsmith17** [rstudio/pyshiny-vscode#7]
I am building Shiny Python apps with VSCode 1.74.3 and Python 3.10.9 in Windows 11. I have confirmed that `shiny` is installed and can be imported. I installed the Shiny extension for VS Code using version 0.0.3. I have created a file called app.py and copied the script for the [basic app](https://shinylive.io/py/examples/#basic-app) on your website. When I go to hit run by clicking the run icon in the top right, I am not presented with a choice to run a shiny app. When I try to run the app, the output in the terminal is simply `python.exe c:/dir0/dir1/app.py` and exits. No app is found at the 127.0.0.1:8000

Any ideas what might be missing? Thanks

**Comment by jcheng5** [comment]
Thank you for the report! I have a fix for this and will test it tomorrow before releasing. In the meantime, you can use Ctrl+Shift+P to launch the command palette, and run "Run Shiny app" from there.

**Comment by jcheng5** [comment]
Should be all set. Thanks again for the report!
